services:
  db:
    image: postgres:15-alpine
    container_name: rollito_db
    restart: always
    environment:
      # Pasa las variables del .env al contenedor
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      # Pasamos estas para que el script 05_roles.sh las pueda leer
      APP_USER: ${APP_USER}
      APP_PASSWORD: ${APP_PASSWORD}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      # Mapeamos la carpeta completa. Docker ejecuta en orden alfabético/numérico.
      # Al mapear la carpeta, nos aseguramos que tome el .sh y los .sql
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: ./web-app
    container_name: rollito_web
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Construimos la URL dinámicamente usando las mismas variables
      DATABASE_URL: postgresql://${APP_USER}:${APP_PASSWORD}@db:5432/${POSTGRES_DB}
